### ISSUE TITLE
Abstract type issues using dynamic xlen in the sail-riscv model

### ISSUE THREAD

**Issue by jordancarlin** [rems-project/sail#1320]
I haven't had the time to create a smaller example or find the root cause, but Sail is occasionally generating SMT constraint files that rely on an abstract type but don't declare it. This is only for the theorem prover backends (SMT, Lean, etc.).

It gives a fairly cryptic error message just indicating that the SMT solver returned an exit code of 1.
```
Error:
riscv_vmem_utils.sail:47.63-106:
47 |function sys_misaligned_allowed_within_exp() -> range(0, 11) = config memory.misaligned.allowed_within_exp
   |                                                               ^-----------------------------------------^
   | SMT solver returned unexpected status 1
```

After adding various debugging statements I found that the SMT solver is failing with the following error message `(error "line 4 column 29: unknown constant zxlen")`, and the input to the SMT solver that generates that error is
```
(push)
(declare-const v0 Int)

(assert (and (= 0 v0) (or (= zxlen 32) (= zxlen 64))))
(check-sat)
(pop)
```

Seems like this might be an issue with how abstract types are being handled because it looks like it is indeed not declaring zxlen.

These error messages are based on the code in https://github.com/riscv/sail-riscv/pull/870.

@Alasdair Assuming this is a Sail compiler bug, this probably needs to be resolved before the new release.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/1322

**Comment by jordancarlin** [comment]
@Alasdair Unfortunately that seems to have broken it more. The new version now gives type errors (with no changes to the code since the previous version) that don't make much sense. Interestingly, I get different type errors for different backends.

For C there are no errors.

When building for smt:
```
Type error:
riscv_xlen.sail:14.11-15:
14 |constraint xlen in {32, 64} 
   |           ^--^
   | Undefined numeric type xlen
```

When building for Lean or Rocq:
```
Type error:
riscv_flen.sail:14.24-38:
14 |type flen       : Int = flen_bytes * 8
   |                        ^------------^
   | Unsupported register type
```

**Comment by Alasdair** [comment]
Can you push a branch that has that error?

With the RISC-V repository I can do:
```
make -C build generated_smt_rv64f
```
and it seems to work

Edit: Nevermind, wasn't on the right branch let me try again...

**Comment by Alasdair** [comment]
Might be fixed by https://github.com/rems-project/sail/pull/1324, unless the Lean and Rocq issue is separate which it might be

**Comment by jordancarlin** [comment]
#1324 fixed the smt issue, but looks like the problem with Lean and Rocq is a separate issue:

```
Type error:
riscv_flen.sail:14.24-38:
14 |type flen       : Int = flen_bytes * 8
   |                        ^------------^
   | Unsupported register type
```

Turning on `dtc-verbose` to try and get more info caused compilation to hang.

**Comment by Alasdair** [comment]
I think the rocq issue should be fixed by https://github.com/rems-project/sail/pull/1327

**Comment by jordancarlin** [comment]
Working with all tested backends now (C, SMT, Lean, Rocq). Thanks for all the fixes!

**Comment by jordancarlin** [comment]
@Alasdair I spoke too soon. It seems like #1327 didn't fully fix the issue. That specific error is gone, but there is now a new instance of the `Unsupported register type` error. This is using the latest version of https://github.com/riscv/sail-riscv/pull/870.

This time it is for a type that directly has the `if ... then ...` clause. It happens for the Lean and Rocq backends.

There is only a type error when xlen is 64. When it is 32 everything works fine. 
```
Type error:
riscv_xlen.sail:22.30-59:
22 |type physaddrbits_len : Int = if xlen == 32 then 34 else 64
   |                              ^---------------------------^
   | Unsupported register type bitvector((if 64 == 32 then 34 else 64))
```

**Comment by Alasdair** [comment]
It looks like the Rocq and Lean backends are relying on constraint simplification always reducing constant expressions to constant values, which it currently doesn't do. That can be fixed fairly easily I think.

**Comment by Alasdair** [comment]
Should be working now

**Comment by jordancarlin** [comment]
Tested the latest fix and all backends seem to working now!
